### ISSUE TITLE
 --plot_track don't work anymore

### ISSUE THREAD

**Issue by roberth1990** [simon-r/dr14_t.meter#41]
I have no idea what is wrong, when I run dr14_tmeter --plot_track, this is just what it returns with:

`Start Plot Track:
Track Title: After Laughter (Comes Tears) 
/usr/lib/python3.6/site-packages/dr14tmeter/plot_track_classic.py:195: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if Y == None and Fs == None and plot_str == None :
/usr/lib/python3.6/site-packages/dr14tmeter/plot_track_classic.py:198: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if plot_str == None and Y != None and Fs != None :
Traceback (most recent call last):
  File "/usr/bin/dr14_tmeter", line 26, in <module>
    dr14tmeter.dr14_tmeter.main()
  File "/usr/lib/python3.6/site-packages/dr14tmeter/dr14_tmeter.py", line 86, in main
    if run_analysis_opt( options , path_name ) :
  File "/usr/lib/python3.6/site-packages/dr14tmeter/dr14_utils.py", line 217, in run_analysis_opt
    spectr.compute_track( path_name )
  File "/usr/lib/python3.6/site-packages/dr14tmeter/audio_analysis.py", line 64, in compute_track
    self.virt_compute()
  File "/usr/lib/python3.6/site-packages/dr14tmeter/audio_analysis.py", line 149, in virt_compute
    plot_str = plot_track_classic( at.Y , at.Fs )
  File "/usr/lib/python3.6/site-packages/dr14tmeter/plot_track_classic.py", line 264, in plot_track_classic
    plot_str.mp[i,:] = np.max( Y[curr_sample:curr_sample+samples_block,:] , 0 )
TypeError: slice indices must be integers or None or have an __index__ method
`

**Comment by simon-r** [comment]
Now it works.
But it seems that the behavior of the mouse events is changed ????
