### ISSUE TITLE
Failed to install on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by wdysun** [simon-r/dr14_t.meter#63]
On Ubuntu 18.04 I tried to install the tar.gz version of the package using 

`sudo python setup.py install --root="/" --prefix="usr" --optimize=1 `

I get the following error
`Traceback (most recent call last):
  File "/usr/bin/dr14_tmeter", line 21, in <module>
    import dr14tmeter.dr14_tmeter
ImportError: No module named dr14tmeter.dr14_tmeter`

I also tried the *.deb version, but it doesn't install saying that I miss the `python-support` package. I tried to install it from pip, but it says that this is a deprecated package.

Any idea?

**Comment by simon-r** [comment]
At the moment you can download the current version from this repo.

I'll try to update the Ububtu package "sooner"

**Comment by wdysun** [comment]
I tried to download the current version on this repo and it gives again

`Traceback (most recent call last):`
`File "/usr/bin/dr14_tmeter", line 21, in <module>`
    ` import dr14tmeter.dr14_tmeter`
`ImportError: No module named dr14tmeter.dr14_tmeter`

**Comment by simon-r** [comment]
try with:
> git clone https://github.com/simon-r/dr14_t.meter.git
> cd dr14_t.meter
> ./dr14_tmeter

**Comment by wdysun** [comment]
Brilliant this worked for me!

Going through the --help I noticed  number of options like --hist, --spectrogram and the like. IHow do you use them on single music file?

Thanks a lot

**Comment by githoober** [comment]
It is not working, it's still giving the  same error:

```
Traceback (most recent call last):
  File "/usr/bin/dr14_tmeter", line 21, in <module>
    import dr14tmeter.dr14_tmeter
ImportError: No module named 'dr14tmeter'
```
